### ISSUE TITLE
pc chrome无法正常使用

### ISSUE THREAD

**Issue by Jamy325** [2fps/recorder#16]
在线演示地址https://recorder.zhuyuntao.cn/
在 pc chrome 版本 67.0.3396.79（正式版本） （64 位） 中
无法录音, 日志为: `异常了,NotFoundError:Requested device not found`
无法播放pcm文件.日志为
`
Uncaught Error: EncodingError: Unable to decode audio data
/example.js:978:9 Error: EncodingError: Unable to decode audio data
at Function../src/recorder.ts.Recorder.throwError (https://recorder.zhuyuntao.cn/example.js:978:15)
at AudioContext.<anonymous> (https://recorder.zhuyuntao.cn/example.js:577:22)
`

**Comment by 2fps** [comment]
你好，请检查下麦克风是否被禁用，或者被其他进程占用。
